### ISSUE TITLE
showing errors on starting dev-watch

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-devkit#1]
When starting gulp dev-watch, it would be convenient if the task could be executed at least once straight away.

For example, if we get an error in my LESS file, gulp stops and needs to be restarted after the error has been fixed. However, checking that the error has indeed been fixed means that you need to start dev-watch, save the LESS file and go back to gulp to check its log.

Having it check that the task can complete on startup would remove 2 steps in this process.

**Comment by julien-gargot** [comment]
I have the feeling that the real thing is to learn how to set correctly gulp to prevent it to crash every time we forgot a `;`.

In your specif case, you can just run `gulp less` before `gulp dev-watch` to see what append.
