### ISSUE TITLE
Duplicate action in gulp task: prefixing CSS

### ISSUE THREAD

**Issue by julien-gargot** [julien-gargot/kirby-devkit#13]
In our gulp, we use `gulp-autoprefixer` but `gulp-cssnano` has a CSS prefixer too. Cf [http://cssnano.co/options/](http://cssnano.co/options/).

I think it’s great to keep `gulp-autoprefixer` because it’s a way to test prefix in a development environment (before minifying). In this case, we should add the `autoprefixer: false` option to the `css` task to avoid a duplicate action running.

What do you think?

**Comment by louis-ev** [comment]
Agreed
We should have the same prefixes for dev and production

**Comment by julien-gargot** [comment]
Done.
