### ISSUE TITLE
A simpler Devkit

### ISSUE THREAD

**Issue by julien-gargot** [julien-gargot/kirby-devkit#16]
###### _Regarding the importance of having a kit that produces a lighter site._

To follow the will of Kirby which tends to be as light as possible, we should reduce our needs to its essentials. Reduce the number of libraries and components to a minimum.
Maybe get rid of Bower that we do not take advantages. Keep only NPM.

_Discuss_ features we use for each project.
_Find_ the best tools to fulfill these features.
_Redefining_ Devkit.

What do you think?

**Comment by julien-gargot** [comment]
Personally, I need:

> 1. CSS reset,
> 2. lightweight Sass grid system<sup>**[1]**</sup>,
> 3. JavaScript that toggles HTML elements<sup>**[2]**</sup>.

<sup>**[1]**</sup> _The grid system I dream of_
- A grid system that can be used from Sass.
- A grid system that can be used from CSS classes.
- A grid system that is responsive.
- A grid system that is mobile first.
- A grid system that can be set in view-port unit, percent, rem, em or pixel.
- A grid system that is aware there are very large screens on the Web today.
- A grid system where I can define the number of columns and gutters.
- A grid system that can be nested by subdividing the container in the same number of columns as the global setting.
- A grid system that can be nested by subdividing the container in a different number of columns than the global setting.
- A grid system that can be nested but where one column always has the same width, no matter the deep nested it is.

<sup>**[2]**</sup> _What I want from a displaying/hiding JS_
- A tool that uses nice customizable CSS animations or transitions.
- A tool that can be used from data-attribute.
- A tool that can be used from JavaScript triggers and events.

**Comment by julien-gargot** [comment]
Until then, I would like to take a look at:
- the _Classic_: [normalize.css](https://necolas.github.io/normalize.css/)
- grid system: [sGrid](http://stylusgrid.com/getting-started.html)
- <del>grid system: [blueprintcss](http://blueprintcss.org/)</del>
- grid system: <del>[960](http://960.gs/)</del> <ins>replace by [unsemantic](http://unsemantic.com/)</ins>
- grid system: [grid-coordinates](https://github.com/adamstac/grid-coordinates)

**Comment by louis-ev** [comment]
I've been thinking about this and with bootstrap 3 now being phased out (see https://github.com/twbs/bootstrap/issues/20631) we desperately need another grid framework soon.

Another grid framework i've tried is semantic-ui, which is not too bad but relied a lot on flexbox I think: http://semantic-ui.com/collections/grid.html

Any new ones you know of we should experiment first?

**Comment by louis-ev** [comment]
Also, would love to get rid of bower and do everything with npm!
Not difficult to do, do we go for it?

**Comment by julien-gargot** [comment]
I have tested a lot Bootstrap 4 (cf. branch), and it’s pretty nice too.

And, yes, for sure, bower is useless.
