### ISSUE TITLE
Improve the .gitignore

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-devkit#17]
How about adding the following two paths to gitignore ? 
Not pushing production assets seems to be appropriate to prevent conflicts.
But can cause trouble if a website is hosted via github directly.

```
/assets/production/*
/assets/css/main.css
```

What do you think ?

**Comment by julien-gargot** [comment]
I’m OK with adding the `assets/production/*` in the gitignore.
For `/assets/css/main.css`, isn’t it better to keep it? Because it is the one loaded in dev environment.

**Comment by julien-gargot** [comment]
Until a CI  deploys the production files on its own, we will retain both versions of the files.
