### ISSUE TITLE
better out-of-the-box experience

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-devkit#18]
Shouldn't we add the output code to the social network menu ?
Something link this, in the footer : 

```
            <ul>
              <?php foreach($site->socialnetworks()->toStructure() as $social): ?>
              <li>
                <a href="<?php echo $social->link() ?>">
                    <i class="fa <?php echo $social->icon()?>" aria-hidden="true"></i>
                </a>
              </li>
              <?php endforeach ?>
            </ul>
```

**Comment by louis-ev** [comment]
Also, maybe a bit of basic type to get started with just enough to not have to write everything from scratch all the time. A very simple css < 15 lines with barely enough, in the spirit of normalize, especially if we abandon bootstrap by default.

**Comment by louis-ev** [comment]
We should also probably set `c::set('debug',true);` in `config.{localhost}.php`

**Comment by louis-ev** [comment]
just did "debug:true" : 0b3d2313e834e7bc4766c3f60f25dd50a95fd6d7
Seemed appropriate considering the purpose of this file

**Comment by julien-gargot** [comment]
Totally agree on the debug variable.
For the social networks, I feel like it’s better to remove them from the site settings. It’s not relevant to a lot of websites. Especially all the ones who don’t give a s**\* of helping private companies to scrap users data. ;) ?

**Comment by julien-gargot** [comment]
Removed social networks.
