### ISSUE TITLE
improve .htaccess with no-index option

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-devkit#19]
Default behaviour of listing all files in /content makes original source files accessible, including invisible folders. Maybe we should prevent that by default?

from: 
![image](https://cloud.githubusercontent.com/assets/1948417/18515764/c95ae868-7a96-11e6-93bb-9817c910083b.png)

to:
![image](https://cloud.githubusercontent.com/assets/1948417/18515805/eb69852c-7a96-11e6-8f66-c1201f0e5104.png)

by adding
`Options -Indexes`
at the end of the htaccess

**Comment by julien-gargot** [comment]
Yes, we can go for it. :+1:
