### ISSUE TITLE
limit the depth of git clone

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-devkit#3]
Add depth parameter in instruction to limit the number of commits inherited from the main repo while forking ? 

See https://www.perforce.com/blog/141218/git-beyond-basics-using-shallow-clones

`git clone --depth`

**Comment by louis-ev** [comment]
What happens with releases ? should we release instead ?

**Comment by julien-gargot** [comment]
Not really sure about the `--depth 1` option interest… This is a developer preference about how using Git :)
