### ISSUE TITLE
browser sync makes panel login disconnect at random times

### ISSUE THREAD

**Issue by louis-ev** [julien-gargot/kirby-devkit#6]
Steps to reproduce : 
- set a localDevUrl
- start gulp dev-watch
- go to the panel
- navigate the panel for a few panel. At some point you'll be asked to login again.

**Comment by louis-ev** [comment]
Not sure where it comes from but it seems to be linked to PHP session w/ browser sync
https://github.com/BrowserSync/browser-sync/issues/637

Maybe due to live-reload ?

Makes browser sync unusable…

**Comment by julien-gargot** [comment]
I cannot reproduce the problem, could it be due to your server configuration?

**Comment by louis-ev** [comment]
Could be. Have to try more

**Comment by louis-ev** [comment]
Tracked the bug a bit more : 

Everytime I login and modify a page, browsersync says in its output : 
`[BS] File changed: site/accounts/louis.php`

but if I disable the path in bold in the browsersync task, panel login stays operational and I am not getting this message anymore : 
`
browserSync.init({
    files: [**'{site}/**/*.php'**, '*.php', userScripts, 'assets/less/*.less'],
    proxy: localDevUrl,
  });
`

So what I think is happening is that somehow browersync watching an account's files is logging out a user. 

A user in the Kirby forum has suggested to use and ignorePaths (see 
https://forum.getkirby.com/t/kirby-gulp-browsersync-sass/3266/5) and I tried setting 'site/accounts/**' as an ignore path but it's not working.

**Comment by louis-ev** [comment]
Fixed thanks to a user on the Kirby forum : https://forum.getkirby.com/t/kirby-gulp-browsersync-sass/3266/7
